version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  logservice1:
    image: logservice
    environment:
      - MONGO_HOST=mongodb
    depends_on:
      - mongodb
    ports:
      - "8081:8080"

  logservice2:
    image: logservice
    environment:
      - MONGO_HOST=mongodb
    depends_on:
      - mongodb
    ports:
      - "8082:8080"

  logservice3:
    image: logservice
    environment:
      - MONGO_HOST=mongodb
    depends_on:
      - mongodb
    ports:
      - "8083:8080"
